language: ruby
rvm:
  - 2.2.0

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role compartilhaco SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database compartilhaco_test;' -U compartilhaco postgres"
  - "bin/rake db:migrate RAILS_ENV=test"
  - "sh -e /etc/init.d/xvfb start"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"

branches:
  only:
    - master

services:
  - redis-server
